version: '3.7'
services:
    backend:
        build:
            context: ./server
            target: 'develop-stage'
        ports:
            - "8080:8080"
        volumes:
            - ./server:/server
        command: /bin/sh -c "cargo watch -x run"
